mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.lindj.model
management:
  security:
     enabled: false

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.253:3306/vcsaas?useUnicode=true&characterEncoding=utf-8
    username: welian
    password: welian
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.46:9092
          zk-nodes: 192.168.1.46:2181
            
